### ISSUE TITLE
Make TINA compatible with bower components.

### ISSUE THREAD

**Issue by polco** [Wizcorp/tina.js#43]

**Comment by bchevalier** [comment]
What is missing to make it compatible with bower?

**Comment by ronkorving** [comment]
PR welcome, I would say :)

**Comment by bchevalier** [comment]
well said

**Comment by polco** [comment]
sure, let me register your own library for you

**Comment by ronkorving** [comment]
Thanks ;)
But uhm, all kidding aside, that json file?

**Comment by polco** [comment]
well i don't need it, i was just making a suggestion. Brice asked me to use his library for feedbacks, that's what i'm doing, I have no intention to go further :)

**Comment by polco** [comment]
Anyway, @bchevalier: http://bower.io/docs/creating-packages/. `bower init` to create the bower.json file and `bower register ***` and that's it.

**Comment by ronkorving** [comment]
With the risk of sounding like an asshole, you should probably stop using bower (if you haven't already). There are better alternatives out there. Could you please provide an update if you would still need this?

**Comment by polco** [comment]
Oh it's fine i don't ! We can close this issue i guess

**Comment by bchevalier** [comment]
:+1:
