### ISSUE TITLE
Easing method expInOut returns NaN

### ISSUE THREAD

**Issue by polco** [Wizcorp/tina.js#44]

**Comment by bchevalier** [comment]
deal with it

**Comment by bchevalier** [comment]
I'm kidding, but that's a good opportunity to contribute

**Comment by bchevalier** [comment]
Yo,

I just tested the method and it seems to work fine. May be you forgot to pass in the parameter?
It should look like this:

``` javascript
var myObject = { x: 0 };
var exponent = 2;

var myTween = new TINA.Tween(myObject, ['x'])
    .to({ x: 1 }, duration, 'expInOut', exponent)
    .start();
```

**Comment by polco** [comment]
oh ok, my bad!

**Comment by bchevalier** [comment]
I guess i could set default value, to make sure all the easing methods work right out of the box.
